[package]
name = "focus_flow_cloud"
version = "1.2.0"
edition = "2021"

[workspace]
members = [
    "crates/domain",
    "crates/application",
    "crates/infrastructure",
    "crates/adapters",
]
resolver = "2"

[dependencies]
adapters = { path = "crates/adapters" }
infrastructure = { path = "crates/infrastructure" }
domain = { path = "crates/domain" }
application = { path = "crates/application" }
dotenvy.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true, features=["ws"]}

[workspace.dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-tree = "0.3.0"
lazy_static = "1.5.0"
regex = "1.11.3"
deadpool-diesel = { version = "0.6.1", features = ["postgres"] }
thiserror = "2.0.16"
uuid = { version = "1.18.1", features = ["v4", "serde"] }
chrono = { version = "0.4.42", features = ["serde"] }
tokio = { version = "1.47.1", features = ["full"] }
utoipa = { version = "5.4.0", features = ["axum_extras", "chrono"] }
utoipa-axum = "0.2.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
axum = { version="0.8.6", features=["ws"]}
tokio-tungstenite = "0.28.0"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
diesel = { version = "2", features = ["postgres", "uuid", "chrono", "r2d2"] }
diesel_migrations = "2"
async-trait = "0.1.89"
http = "1.3.1"
tower-http = { version = "0.6.6", features = ["trace", "cors"] }
tower = { version = "0.5", features = ["util"] }
validator = { version = "0.20.0", features = ["derive"] }
rand = "0.8"
config = "0.13"
matchit = "0.8.4"
tower-sessions = { version = "0.14.0", features = ["memory-store"] }


# Dev dependencies
[dev-dependencies]
tokio-test = "0.4" # Not in workspace yet
http-body-util = "0.1" # Not in workspace
mockall = "0.11" # Not in workspace
testcontainers = "0.23" # Not in workspace
testcontainers-modules = { version = "0.11", features = ["postgres"] } # Not in workspace
reqwest = { version = "0.12", features = ["json"] } # Not in workspace
serde_json.workspace = true
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
